### ISSUE TITLE
peco

### ISSUE THREAD

**Issue by davmaz** [mattn/memo#14]
Nice program! I'm on Ubuntu Linux 14.04 -- what is equivalent of peco so I can edit my memo?
Also, is there a way to more simply show the complete memo?
In other words, I create the memo with vim, but it would be nice to have something like this:
memo new
debug
vim edit file and add several lines about debug, then save file.
memo show debug (which would basically cat my vim created file relating to debug)

**Comment by mattn** [comment]
See README.md
