### ISSUE TITLE
view memo

### ISSUE THREAD

**Issue by lanox** [mattn/memo#23]
It would be nice if you can view the memo rather having to go and edit it to see the conten, or that feature is there already.

**Comment by mattn** [comment]
`memo serve` start web sever that can look the text as markdown.

**Comment by lanox** [comment]
I got that, but would be nice to view the memo from cli. I think its more faster/better to have it all in cli at least my 5c worth.

**Comment by luv2code** [comment]
I wrote a little plugin in bash to view the output formatted:
I put an executable file called `view` in my plugins dir with this content:
```bash
#! /usr/bin/env bash

arg=$1
note=""

echo "note $arg"

if [ -z $arg ]; then
  note=$(ls $MEMODIR | peco)
else
  note=$arg
fi
note="$MEMODIR/$note"
echo "viewing $note"
echo ""
cat $note | marked | elinks --dump
```

This requires three external tools to be installed:
* `peco`: `apt install elinks` - for choosing files
* `marked`: `npm install --global marked` - for taking gfm input and outputting html
* `elinks`: `apt install elinks` - a cli web browser. the `--dump` option takes html on stdin and formats it for CLI.
