### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by abeq** [mattn/memo#51]
with following message:
```
package github.com/urfave/cli/v2: cannot find package "github.com/urfave/cli/v2" in any of:
        c:\go\src\github.com\urfave\cli\v2 (from $GOROOT)
        C:\Users\user\go\src\github.com\urfave\cli\v2 (from $GOPATH)
```
Please check and fix it, thank you.

**Comment by mattn** [comment]
What version of Go do you use? and do you set GO111MODULE?

**Comment by abeq** [comment]
Install success with setting GO111MODULE environment variable.
I appreciate for your great support.
