### ISSUE TITLE
`memo grep` won't work well with Select-String on Windows Powershell

### ISSUE THREAD

**Issue by squeuei** [mattn/memo#56]
`memo g` command causes a loop of displaying results when `grepcmd` is set as below.

    grepcmd = "powershell Select-String -Pattern ${PATTERN} -Path ${DIR}/*.md"

- OS: Windows 10 Pro / Windows 11 Pro
- Terminal: Powershell on Windows Terminal

On line 720 of `main.go`, `func cmdGrep` has a `if` block for Windows environment and it seems to be the cause. I don't know why the block is there but I imagine that it's necessary workaround when `grep` is used on `cmd.exe`.
Actually, I'm not using `grep` despite the name of config so that it is very understandable if this issue is regarded as inappropriate. However I would be happy if I can use `Select-String` here because powershell commands are available on Windows 10/11 by default.
Is there any good way to support both `grep` and `Select-String`?

**Comment by mattn** [comment]
Could you please try https://github.com/mattn/memo/pull/57 ?

**Comment by squeuei** [comment]
Tried `go install github.com/mattn/memo@fix-56` and it worked flawlessly. I appreciate your quick response, and of course providing this nice tool.
Happy holidays!
