### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by anatollupacescu** [mattn/memo#8]
`anatol@anatol-CT15:~$ go version`
`go version go1.6.2 linux/amd64`

`anatol@anatol-CT15:~$ export GOPATH=~/.go`
`anatol@anatol-CT15:~$ go get github.com/mattn/memo`
`# github.com/shurcooL/github_flavored_markdown/gfmstyle`
`.go/src/github.com/shurcooL/github_flavored_markdown/gfmstyle/assets_vfsdata.go:136: undefined: io.SeekStart`
`.go/src/github.com/shurcooL/github_flavored_markdown/gfmstyle/assets_vfsdata.go:138: undefined: io.SeekCurrent`
`.go/src/github.com/shurcooL/github_flavored_markdown/gfmstyle/assets_vfsdata.go:140: undefined: io.SeekEnd`
`.go/src/github.com/shurcooL/github_flavored_markdown/gfmstyle/assets_vfsdata.go:181: undefined: io.SeekStart`
`anatol@anatol-CT15:~$ ls .go`
`pkg  src`

**Comment by mattn** [comment]
Please upgrade go to 1.7.

**Comment by mattn** [comment]
Or you can download binary from https://github.com/mattn/memo/releases

**Comment by anatollupacescu** [comment]
It works, thanks
